### ISSUE TITLE
cannot use _Ctype_ulong(dur) (value of type _Ctype_ulong) as _Ctype_ulonglong value in assignment

### ISSUE THREAD

**Issue by c1ngular** [OmegaRogue/gotk4-gstreamer#2]
tried running example(from both master and develop branches) hangs with error on Apple M1 Pro (go version : 1.20.5): 

github.com/OmegaRogue/gotk4-gstreamer/pkg/gst ../../gst/gstbuffer.go:2278:17: cannot use _Ctype_ulong(dur) (value of type _Ctype_ulong) as _Ctype_ulonglong value in assignment

**Edit :**

../../gstvideo/video-frame.go:75:2: VideoBufferFlagOnefield redeclared in this block
	../../gstvideo/video-frame.go:56:2: other declaration of VideoBufferFlagOnefield
../../gstvideo/video-frame.go:165:2: VideoFrameFlagOnefield redeclared in this block
	../../gstvideo/video-frame.go:154:2: other declaration of VideoFrameFlagOnefield
../../gstvideo/videooverlay.go:398:23: cannot convert unsafe.Pointer(handle) (value of type unsafe.Pointer) to type C.ulong
../../gstvideo/videooverlay.go:509:23: cannot convert unsafe.Pointer(handle) (value of type unsafe.Pointer) to type C.ulong
../../gstvideo/videooverlay.go:605:23: cannot convert unsafe.Pointer(handle) (value of type unsafe.Pointer) to type C.ulong

...more

@OmegaRogue

**Comment by OmegaRogue** [comment]
iirc this error had to be fixed manually, i thought i included code to do that, you can check if maybe i commented it out

**Comment by c1ngular** [comment]
@OmegaRogue  thanks for reply ,  I have given up since these go bindings are way too complicated for me and my use case . 

Thanks again .

**Comment by OmegaRogue** [comment]
> @OmegaRogue  thanks for reply ,  I have given up since these go bindings are way too complicated for me and my use case . 
> 
> Thanks again . 

I have cgo bindings around somewhere that do the same but less cleanly
